---
- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
      - stx-bandit-jobs
    check:
      jobs:
        - openstack-tox-linters
        - stx-distcloud-tox-pep8
        - stx-distcloud-tox-py39
        - stx-distcloud-tox-pylint
        - stx-distcloud-tox-black
        - stx-distcloud-tox-cover
        - stx-distcloud-tox-openapi-check
    gate:
      jobs:
        - openstack-tox-linters
        - stx-distcloud-tox-pep8
        - stx-distcloud-tox-py39
        - stx-distcloud-tox-pylint
        - stx-distcloud-tox-black
        - stx-distcloud-tox-cover
        - stx-distcloud-tox-openapi-check
    post:
      jobs:
        - stx-distcloud-upload-git-mirror

- job:
    name: stx-distcloud-tox-py39
    parent: tox-py39
    description: Run py39 for distcloud
    nodeset: debian-bullseye
    pre-run:
      - tools/gate/playbooks/install-postgresql.yaml
      - tools/gate/playbooks/install-stx-custom-deps.yaml
    required-projects:
      - starlingx/fault
      - starlingx/nfv
      - starlingx/update
      - starlingx/config
      - starlingx/root
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: py39
      tox_extra_args: -c distributedcloud/tox.ini

- job:
    name: stx-distcloud-tox-pylint
    parent: tox
    description: Run pylint for distcloud
    nodeset: debian-bullseye
    required-projects:
      - starlingx/fault
      - starlingx/nfv
      - starlingx/update
      - starlingx/config
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: pylint
      tox_extra_args: -c distributedcloud/tox.ini

- job:
    name: stx-distcloud-tox-pep8
    parent: tox
    description: Run pep8 for distcloud
    nodeset: debian-bullseye
    required-projects:
      - starlingx/fault
      - starlingx/nfv
      - starlingx/update
      - starlingx/config
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: pep8
      tox_extra_args: -c distributedcloud/tox.ini

- job:
    name: stx-distcloud-tox-black
    parent: tox
    description: Run black for distcloud
    nodeset: debian-bullseye
    vars:
      python_version: 3.9
      tox_envlist: black
      tox_extra_args: -c distributedcloud/tox.ini

- job:
    name: stx-distcloud-tox-openapi-check
    parent: tox
    description: Check that the committed OpenAPI spec is up to date
    nodeset: debian-bullseye
    vars:
      python_version: 3.9
      tox_envlist: openapi-check

- job:
    name: stx-distcloud-tox-cover
    parent: tox
    description: Run coverage test for distcloud
    nodeset: debian-bullseye
    required-projects:
      - starlingx/fault
      - starlingx/nfv
      - starlingx/update
      - starlingx/config
      - starlingx/root
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: cover
      tox_extra_args: -c distributedcloud/tox.ini
    post-run: tools/gate/playbooks/fetch-coverage.yaml
    voting: false

- job:
    name: stx-distcloud-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/distcloud to
      github.com/starlingx/distcloud
    vars:
      git_mirror_repository: starlingx/distcloud
    secrets:
      - name: git_mirror_credentials
        secret: stx-distcloud-github-secret3
        pass-to-parent: true

- secret:
    name: stx-distcloud-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - tC+Fwsn1hBN7kCkW/c2NOjVH4m6ty2/B88Z+VQLqPkOH0RPjQcOd3GX6POm7RipCV24pj
          0+pMh4XlMQNmK9VVo3YjRPBIBFEKUhcv7w7Z/Ud2aukE8eLqM65aPcIOEFobYgePhYJZT
          RNtEVO7FyrzblrLTkWptA6nyz0fIQwHzCesaWGrzmVN1c0Tuc96wT8aKsHMKVGk1H8eVd
          zgmsoWkGCWLQnRJ9Y+XQagPxA8CiG8ujj2gHZfknQgig+I1muKI9fEKzBI9Xt/CjRPuK3
          jXGgNjioOA3TPZAQhdMTMC582jIA6L8KVNestRNJh8kVH8lC8BaBAaOh/oRlDBr1XbJ9Y
          FVmDtuqFdGbx03A1DyxH4uRpVoEdAQZ3vAOjeFiFYMfnbWlrEnjLXSq0GMGmwnpAhC6ys
          +4bp2tMgLFE1aueIHbU+48zkVe2wTHp85Yx8KYPUNeyKzgFv65jmF7h1sYD0/y4C5KI91
          Hafi7MNcRX/qtbYZ2aviAoOYTLTZVTpl37jybLxAXTZtQaZa3O/qsWjK3Bo4ketys4N+c
          H+vmOS3oMLLjXOqhQAfE+6muAX4vVkMAsKu0gSurPzJf/xiuxCdJ+2MavM12BJvO8llYF
          6jYzrWt7ChHTDYexUNvKthqK9oZAxKM7ngzdimBVCnch3FZbZdZGCcCk9c5RQk=
        - Aei4YEkWf+9tcG6268cnnG8dQLsZKSS38UY1xZ7i77Z3pr86HBu2Mqg/6cZoQDaSPUAi7
          1jUvpY+RCmot+9yu2PsPqI4wD06D/zpjBRvNVgiiHrrAn8DZNYf06lAo+JZbw2eqDZaUQ
          ELbuHYt3DG9sw/+T4DsDlN74W1fxhHwAqOWlLWQPWkKznArGj+fw5L365C6vW/i7cs+RS
          t5AH1ci0U6lndB7d+Sd0cin6wvNabkpP1IPvoOyyxGppCbp6VzaahnFdgdsjt/w8YSVIf
          yzDs7rRu/OjrgCUjxqfkyoVReflRpgCcWDiTjwDYov2gKFn8BnBns1ukA6FFJgVmwE91z
          M06NqgAyvMtAGsezJdO7yw3K5c8RLSe1x2nvXrOrQuxNeJ5Itfrp7qwQi1I9pyaZe5lVm
          jqh8WLq3ATyEppA2v0pjHhGavxnu3s40PN1bwh1K+h6JyIKPvkZ/j/7iaLp4t1EYC/A37
          ff+c1eh8VcZ4Yt7MKtpPX5b+9MTAtsGpNv0vMCjNz393zveNdWaC+Jlyxc0qjPp9RVYyd
          HIPki0Cen5KzueuuKyMMhRrj39DBobs9acYM/uwVY88Zu0wz3Kj2jpDbwNl2eIyZp5L9q
          GCls6tnuykWNvH37Ywv327wmpKjc0GqY1QyYZQa4+mfkWhoPOqGBS2s6cRO/zM=
        - LDMq0Tsu/3kCqN2v2JzjRBkRiMqD7hCv0LuY2wTJKKHU2hbnbgkFn8HL8QF5+3UXNa/xw
          Ha3VHV1JARofICJ7BjxsBK5uptUh1QdH0WatVXhZgJvNlzc2vbj0KX1yYlIwoY9Ok65s4
          /qKU8xgFNOIMWn3ANwxDlnt25gFUKkZvEovaa9hK/uyw6YHBCYormksvUOffk38q2nCnS
          IEEGr+Myk4X+H9UdEAmYZlwzoHklAKs4TNj/S4eR3L8W0j70iDpzQCxSrLtuHH1MOHNOV
          ATOMYgJBY1btlUC+bcrMt2J/iD6FQoqjoHqeV1iybAY6vcD3jNYfk6UDwxzaT90Wop4wE
          F5X2nOWa6WcpE6rf2FIXaYRpzFbMywb21vI7m91qh9Ya19d2d5OiI9kkhJm+hOZ72cGL9
          m2yEOjuFKH0a5kcWakvZm5tukKNSkVnTeAfCAmwlWsqsWu0+cZEYQT3Jw6mml14+CCc4C
          +fowY9e4LLUSpgVFEHwnCqFkB8UtnuElzszP2NphrHbuoLMxx67mRh+F4JQLYDMQq6kOK
          iq+uin/tlHMlf1k/pbejF356OYsHkVFzcVz8pfTbot8vgkboSRAlBAeRtNUYGUpzqrh5T
          dwFw+uTqyAPuCVzhv9cjUxVImcNaRlyeH0MYE9Ygz2F/Qk3Er+nDnROD48hcac=
        - RhgHdV0DjWs51nqX69cwt66kyj8x+GlZ+PUiVKu9rEjGaXaYtr3sIj4oiyufrwiQvDH71
          vvVGzQAOxxe+3nD42Fdz+vCtRGT6agmOdLJ0tXNoxR4qwcSHBgiPeRJTCj2LNuOIDHjQi
          /g7ffY/Vr4xWnI2nAcD7dPDUaywP3jK08RGkD4bi9nGxNyN7rZH4ePnGfWqmxalbjgbZL
          DsQhKHONIkV0X1LOxmMKGmkUn3HzD0HdumeHejInFDUi8xOVvZq847HWaKE0lUNbJMFMy
          Pyh1scWqGQBlCUecv/gqe3oqGcz4NuQc7jVYjBgRx7xw/SBFggKGbFEQKn+UUjq52jSO/
          TdCVPXfYpZE4jOtu4XKRHz/8XVisirKSuVzsma2891HSMINlcW1toiTj4PHNa8kU910QV
          9gD7GMcp4uJQkNAVMMfXBsSSCTYCTZzVJO74vvsEMp1Y4HureZEAWRY+wMW/wYnmG8TCJ
          pc/8wfT191+oqLujiPxQoeBrvfl4in3F5x9LWtPsdpRKuSBIKjeo1KzylNhU9/0R/9nOw
          VVwBHxjVvEhKwvul+rCZruHqpHoCT+lSNdefrkk+qqPufDRM0cxP3QUlyNd3X4FsWCSpu
          lGmW0SYcdZu4BdrzY08LSwORn9NvzjLeLkL6EsQpZs1GZlh5KHHlZVsxOjZhco=
        - laKA2k1w1JZQaDZI/5QW2rYGAaRT3S4sseRB5uW2+6qpts0w+dUdI880BdwHR1DfbjTkp
          wswd1eqr0Ac/1jRCMax1H0b9s5E7XLhHYl5d/i1J/t5BSZIDYL2+iU1MahUcTWzp+Qz9f
          f3mloTLZy8Xzd8u2Qygvj6dbIgR+8mJoxo/UPUqrS8c6UQ/S0tQ2itN6rPwo+ORkPArgo
          wIj+sq3efpGpnRtPFPK0ERbr/1eGX11KljWDNIgyGm9XDeRKY8Xi1fJn2N46kCFFSfXu9
          PFaWuE+2RnNicb4qaAzM5Hw2k9t8OzriABgHQxUjAFJEJJ3u1Kn9PC8AJSthvnSp2Gz5V
          Hz/nZAWTycW7v3jIjmpZlPNe1Lww8+VrR/2bd10iRlRRELDIV2V7WA1X4tCBa6sKpws66
          83kal2R/Ct1/sYU9WEWWtYTZcDvFIicl8rR95LerYgBLtf7w6B+3YFtQuWHXVmBJpXMRZ
          I+u/dpPTpWgVafabkUQGGkVn9ivFppzjg6a0seeDc7PlvOagmVeiTi7oCFPi0Eveacili
          V/9s08tW8Gy5Rh4g9I6ShTRt+qzDuupcmLwLsa4r9FdqlUL5MOKTmqPvy1cOPx0KO7rA7
          G7hMUM6Scl69ZsTmNnfOFw+bTw7+nJOSGekwXKYEJUCHFDsSYtR6i7Ua04rZSA=
        - Bp4eSgaXTehJwNtFyKIJHVqJzqEuLl1xodDjdoLG6ra7eQ6j2Xdjf7P8/1z53hLUriM5B
          D9W5WyCgGqBocXuKixeAOfKMfFVICbAZI3daAnV9oT+kAebkdbAwZy1EXqFgRLuR0YHEN
          a+se6tF6Z2l0HtCLeflp3oxPZVlhna5lhKHsFf2E1g6rb9yE/e6MPazNIkq+hV9eb499+
          90VQbJpKT961X8TQRG5FvFMtLWmEWgSM37XeqzLy9ADJXlvtKRLhOvEgjiWjbVLr2TI5w
          rxqM2uGhLqRG89QAem9+umJsyZa6cwEGjxOiGoTaudCjuOzABwkcSG9k2oP0ruGB/Sj8r
          LvR2JcEi/17KVM/Ez2Pa1yntZgYorYH380JJNi6aEcw3BSMY48byhYOqnUWCc1Dzp/fDR
          6+eEFGJwEcfHdBn6X1j63bl7+7Pp/Y8nk6+M5OjBk0wOMCHF23YUi0ap2Uwh6BJ8PI81e
          LAly2/hQOv9I1+hBZRgHK03BdoA2HBn2ppPYFWxGVfnDrIXXBHMbYGjejTcgA5hOHvx6i
          PbqbUEIebyD0EHFQ88HuG93ax5DEeVJzU8SZtkwCdI314BYnYrjTyvHv0qzEW3cn/ccNy
          2zeJtTOjKgYgxY8BI2wWyflF0kr5Bx79uRU5EPVeerQnRlWGdraZDmqevLPncQ=
        - olUAqqVVluAcvZ3JoYXuSXFVxO5rRDwl8lkyG9idlzblwXAGTp4WQ5pydRWv6BPuLNRJd
          +nR7VWcZJu9Y24bLAdnwfDWSC2X3aM3qqKj+w2Y8qvz2+JeFDwZfsRDT5zH1Vz3cN6jZ5
          DFFRB55i1Vr/ovrWxA1LSZ9Oj0KdjZbRDubYqlwUKDbxOU4VQe0ivw92q9Ey7IJd5025f
          kWZojTp3CWbpODPtE7l4cCxjgbt6brTB7vWUEqKO4rxPMkW5gqcVdRB+fvY7sXSQyEpxP
          8/pLwgAgtDm5TkRDuCuEYs9yq2+7Rg7wcFS0Q81L0flBDfkiRlNlqReWsTagcvlY6Q/NZ
          dtl7J4fxaKc2PYynZIWv0t4+IzdpvuLZP5bpIvRhjtvrQc3htflCAMpO8VDK0qsugsN+n
          7wtB+kEMRxXXY1DU2h8MMTSP8kjTJE3ZNvggrb0QGFhjq/9RB4cGJ1b6wTqw9xZjGzIYF
          Jliuhy7PKch4IKl024xmZC+1vRqFrUA+cHDlzuWV9/d/cegRD0R0hbWXpYlaL3G6Daexb
          F11kFU63bE3vLQDAjYZIMUyPiHDa5rcU7JFsrjlSd4N1y/UyoX5/fwmNNDrKMGWyG/2G1
          VxOQKf+CWiIiYVd4QTjpbIsEOc+7l3FwguphAyAbHF3xck7PmZJZha3AOOJttU=
