---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8:
            voting: false
    gate:
      jobs:
        - build-openstack-releasenotes
        - openstack-tox-linters
