#
# Copyright (c) 2024-2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

import http.client
import ipaddress
import json
import os
import socket
from urllib.parse import urlparse

from oslo_config import cfg
from oslo_log import log as logging
import pecan
from pecan import expose
from pecan import request

from dcagent.api.controllers import restcomm
from dcagent.common.audit_manager import RequestedAudit
from dcagent.common.exceptions import UnsupportedAudit
from dcagent.common.i18n import _
from dccommon import consts as dccommon_consts

CONF = cfg.CONF
LOG = logging.getLogger(__name__)


class AuditController(object):
    @expose(generic=True, template="json")
    def index(self):
        # Route the request to specific methods with parameters
        pass

    @index.when(method="PATCH", template="json")
    def patch(self):
        """Return the audit information."""

        context = restcomm.extract_context_from_environ()

        # Convert JSON string in request to Python dict
        try:
            payload = json.loads(request.body)
        except ValueError:
            pecan.abort(http.client.BAD_REQUEST, _("Request body decoding error"))

        if not payload:
            pecan.abort(http.client.BAD_REQUEST, _("Body required"))

        # Remove extra_args from the payload (used for backward-compatible
        # extensions such as OIDC login config sync)
        extra_args = payload.pop("extra_args", {})

        # Sync OIDC login config if provided by the system controller
        # via extra_args.
        oidc_login_config = extra_args.get("oidc_login_config")
        if oidc_login_config:
            self._sync_oidc_login_config(oidc_login_config)

        LOG.debug(
            f"Payload sent by system controller: {payload}. Extra args: {extra_args}"
        )

        try:
            # Delete "use_cache" from payload so it doesn't get passed as an audit
            use_cache = payload.pop("use_cache", True)
            # request_token is used for calls not involving cache
            requested_audit = RequestedAudit(
                request_token=context.auth_token, use_cache=use_cache
            )
            return requested_audit.get_sync_status(payload)

        except UnsupportedAudit as ex:
            LOG.exception(ex)
            pecan.abort(http.client.BAD_REQUEST, ex.msg)
        except Exception as ex:
            LOG.exception(ex)
            msg = f"Unable to get audit info: {ex}"
            pecan.abort(http.client.INTERNAL_SERVER_ERROR, _(msg))

    @staticmethod
    def _extract_oidc_issuer_host(content):
        """Extract the hostname from oidc-issuer-url in the config."""
        for line in content.splitlines():
            if line.startswith("oidc-issuer-url:"):
                url = line.split(":", 1)[1].strip()
                return urlparse(url).hostname
        return None

    @staticmethod
    def _addresses_match(addr1, addr2):
        """Compare two IP addresses for equality, handling IPv6 normalization.

        Uses ipaddress module to ensure equivalent representations of the
        same address (e.g., '2620:10a:a001:aa0c::54' vs
        '2620:10a:a001:aa0c:0:0:0:54') are recognized as equal.
        """
        try:
            return ipaddress.ip_address(addr1) == ipaddress.ip_address(addr2)
        except ValueError:
            return addr1 == addr2

    @staticmethod
    def _sync_oidc_login_config(content):
        """Write OIDC login config to local file if content has changed.

        This is called during the audit cycle when the system controller
        includes the OIDC login config in the audit payload. The file is
        only written if the content differs from what's already on disk.

        If the subcloud has oidc-auth-apps applied locally, its config
        file will have oidc-issuer-url pointing to the local OAM IP.
        In that case, the file is not overwritten to preserve the
        subcloud's own configuration.
        """

        config_path = dccommon_consts.OIDC_LOGIN_CONFIG_PATH
        try:
            if os.path.isfile(config_path):
                with open(config_path, "r") as f:
                    existing_content = f.read()

                # No change needed
                if existing_content == content:
                    return

                # If the existing config's oidc-issuer-url points to this
                # host's OAM IP, it was generated by a locally-applied
                # oidc-auth-apps. Do not overwrite.
                existing_host = AuditController._extract_oidc_issuer_host(
                    existing_content
                )
                if existing_host:
                    try:
                        results = socket.getaddrinfo("oamcontroller", None)
                        local_oam_ip = results[0][4][0] if results else None
                    except socket.gaierror:
                        local_oam_ip = None

                    if local_oam_ip and AuditController._addresses_match(
                        existing_host, local_oam_ip
                    ):
                        LOG.debug(
                            "Skipping OIDC config sync: subcloud has "
                            "local oidc-auth-apps (issuer-url points "
                            "to local OAM %s)",
                            existing_host,
                        )
                        return

            tmp_path = config_path + ".tmp"
            with open(tmp_path, "w") as f:
                f.write(content)
            os.chmod(tmp_path, 0o644)
            os.rename(tmp_path, config_path)
            LOG.info("OIDC login config synced from system controller")
        except Exception as e:
            LOG.warning(f"Failed to sync OIDC login config: {e}")
