#!/bin/bash

set -x

PKG_BUILD_NAME=$1
PKG_BUILD_DIR=$(realpath `pwd`/${PKG_BUILD_NAME})

STX_BASE=$(realpath ${MY_REPO}/stx)
PKG_BASE=$(realpath ${STX_BASE}/distributedcloud/distributedcloud)

mkdir ${PKG_BUILD_NAME}

cp -r ${PKG_BASE}/* ${PKG_BUILD_DIR}/

mkdir ${PKG_BUILD_DIR}/files
cp ${PKG_BUILD_DIR}/centos/files/* ${PKG_BUILD_DIR}/files/

rm -rf ${PKG_BUILD_DIR}/centos
